3_part_without_review
YaTut1901/internet_shop pull request #3
Opened 2020-09-08 13:51 UTC by YaTut1901

2020-09-08 14:41 UTC, DariaPikul requested changes
Generics?..

2020-09-08 14:41 UTC, DariaPikul commented on src/main/webapp/WEB-INF/views/index.jsp
> +--%>
I find it confusing that you're Sergey now, Ivan... So let's remove that

2020-09-08 14:41 UTC, DariaPikul commented on src/main/webapp/WEB-INF/web.xml
> +</web-app>
Blank line!

2020-09-08 15:04 UTC, DariaPikul approved these changes

2020-09-09 06:18 UTC, RomanDubovskyi reviewed
Some files from hw is missing, for example where is GenericDao class in PR ?

2020-09-09 12:59 UTC, RomanDubovskyi commented
insert new link please

2020-10-14 10:01 UTC, closed without merging